### ISSUE TITLE
Odd bug when running `use`

### ISSUE THREAD

**Issue by Shackelford-Arden** [Shackelford-Arden/hctx#16]
A friend mentioned this to me. Here's the output he got from the error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x86f81b]

goroutine 1 [running]:
github.com/Shackelford-Arden/hctx/cmd.Use(0xc000165b38?)
    /home/runner/work/hctx/hctx/cmd/use.go:33 +0x87b
github.com/urfave/cli/v2.(*Command).Run(0xc00010c420, 0xc000233cc0, {0xc00023cd20, 0x2, 0x2})
    /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x97d
github.com/urfave/cli/v2.(*Command).Run(0xc00010cf20, 0xc0000a72c0, {0xc000092240, 0x3, 0x3})
    /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xbb7
github.com/urfave/cli/v2.(*App).RunContext(0xc00019e000, {0xa16970, 0xda0a40}, {0xc000092240, 0x3, 0x3})
    /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x58b
github.com/urfave/cli/v2.(*App).Run(0xc0000061c0?, {0xc000092240?, 0x40a22b?, 0x0?})
    /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311 +0x2f
main.main()
    /home/runner/work/hctx/hctx/main.go:17 +0x85
```

I'm guessing that it has something to do with the stack that was already selected. Looks like something maybe happened with the caching. Most likely that `currentCache` is `nil` here:

https://github.com/Shackelford-Arden/hctx/blob/main/cmd/use.go#L25

**Comment by Shackelford-Arden** [comment]
Should be all fixed in 1.3.0 but I'd go ahead and pick up 1.3.1 😎
